___

<a href='https://mainacademy.ua/'> <img src='https://mainacademy.ua/wp-content/uploads/2019/03/logo-main.png' alt = 'Хмм, щось з інтернетом'/></a>
___

# Module 5: Data analysis with NumPy and Pandas

## Lab work 5.1



#### Мета: 

* навчитися працювати із бібліотекою NumPy в Python

### Завдання:

In [1]:
import numpy as np

## Вивести версію та конфігурацію бібліотеки:

In [5]:
np.__version__
np.show_config()

blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    library_dirs = ['D:\\a\\1\\s\\numpy\\build\\openblas_info']
    libraries = ['openblas_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
blas_opt_info:
    library_dirs = ['D:\\a\\1\\s\\numpy\\build\\openblas_info']
    libraries = ['openblas_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    library_dirs = ['D:\\a\\1\\s\\numpy\\build\\openblas_lapack_info']
    libraries = ['openblas_lapack_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
lapack_opt_info:
    library_dirs = ['D:\\a\\1\\s\\numpy\\build\\openblas_lapack_info']
    libraries = ['openblas_lapack_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
Supported SIMD extensions in this NumPy install:
    baseline = SSE,SSE2,SSE3
    found = SSSE3,SSE41,POPCNT,SSE42,AVX,F16C,FMA3,AVX2
    not found = AVX512F,AVX512CD,AVX51

## Створити вектор з 10 елементів, заповнений одиницями:

In [6]:
a = np.ones(10)
print (a)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


## Створити вектор із значеннями від 0 до 10:

In [12]:
b = np.arange(0,11)
print (b)

[ 0  1  2  3  4  5  6  7  8  9 10]


## Створити матрицю 5 на 5, заповнену нулями:

In [17]:
c = np.zeros ((5,5))
print (c)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


## Заповнити вектор з 20 елементів випадковими цілими числами. Знайти індекси ненульових елементів:

In [129]:
d = np.random.randint(20, size = (1,21))
print (d)
#np.where(d == 0)[0]
index= np.nonzero(d)
index

[[13  0 18  1  9  9  6  2  8  6 15  7  2  9 14  1  5  3 17 13 10]]


(array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       dtype=int64),
 array([ 0,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20], dtype=int64))

## Для вектора із попередньої задачі знайти середнє значення, медіану, стандартне відхилення:

In [62]:
print ('Cереднє значення: ', d.mean())
print ('Медіана: ', np.median(d))
print ('Стандартне відхилення: ', d.std())

Cереднє значення:  44.45
Медіана:  39.5
Стандартне відхилення:  25.336682892596656


## Створити дві матриці випадкових чисел розміром 4х2 та 2х2. Перемножити їх:

In [130]:
e = np.random.randint(50, size = (4,2))
print ('First matrix:')
print (e)
f = np.random.randint(50, size = (2,2))
print ('Second matrix:')
print (f)
g = np.dot(e,f)
print ('Result: ')
print (g)

First matrix:
[[40 41]
 [36  8]
 [27 40]
 [10 43]]
Second matrix:
[[10 46]
 [ 6  6]]
Result: 
[[ 646 2086]
 [ 408 1704]
 [ 510 1482]
 [ 358  718]]


In [136]:
g1 = np.reshape(f, (4,1)) * e
print ('Result: ')
print (g1)

Result: 
[[ 400  410]
 [1656  368]
 [ 162  240]
 [  60  258]]


## Результуючу матрицю із попередньої задачі перетворити у вектор. Знайти мінімальне та максимальне значення. 

## Максимальне значення замінити на 0:

In [141]:
h = np.reshape(g1, (1,8))
print (h)
print ('Мінімальне значення: ', h.min())
print ('Максимальне значення: ', h.max()) 
h [0][2] = 0
h

[[400 410   0 368 162 240  60 258]]
Мінімальне значення:  0
Максимальне значення:  410


array([[400, 410,   0, 368, 162, 240,  60, 258]])

## Знайдіть кореляцію першого рядка матриці із попереднього завдання із іншими рядками:

In [151]:
print (g1)
np.corrcoef(g1, rowvar=False)

[[400 410]
 [  0 368]
 [162 240]
 [ 60 258]]


array([[1.        , 0.45482393],
       [0.45482393, 1.        ]])

## Дано матрицю. Знайти ранг матриці:

In [93]:
a = np.array([[ 1,  4, 5],
              [7, 3, 2],
              [9, 16, 1]])
rank = np.linalg.matrix_rank(a)
print ('Ранг матриці a: ', rank)

Ранг матриці a:  3


## Знайти визначник матриці:

In [95]:
print('Визначник матриці а: ', np.linalg.det(a))

Визначник матриці а:  440.0000000000002


## Знайти власні значення та власні вектори матриці: 

In [99]:
own = np.linalg.eigh (a)
print (' Власні значення та власні вектори матриці a: ')
print (own)

 Власні значення та власні вектори матриці a: 
(array([-14.30540864,  -4.34740072,  23.65280936]), array([[ 0.15315575,  0.88160309,  0.44645191],
       [ 0.63674998, -0.43353159,  0.6376518 ],
       [-0.75570681, -0.18661821,  0.62775861]]))


## Знайдіть число, що найчастіше зустрічається в масиві:

In [103]:
a = np.random.randint(0,10,50)
print ('Масив: ', a)
print('Найчастіше зустрічається в масиві число: ', np.bincount(a).argmax())

Масив:  [3 5 7 3 3 0 7 2 1 9 9 3 1 1 5 2 7 5 3 1 5 3 2 7 4 0 3 8 7 2 2 0 9 8 8 1 4
 0 5 0 1 1 2 7 3 4 1 1 3 3]
Найчастіше зустрічається в масиві число:  3


## Виведіть лише парні числа, що діляться на 5:

In [113]:
a = np.random.randint(0,10,50)
for i in range(10):
     if i%5==0:
        print (i)

0
5


## Розв'яжіть систему рівнянь:
$$2x + 5y = 1 $$

$$x - 10y = 3  $$
   

In [107]:
M1 = np.array([[2, 5], [1, -10]])
v1 = np.array([1, 3])
results = np.linalg.solve(M1, v1)
print ('Відповідь: ', results)

Відповідь:  [ 1.  -0.2]
